name: CI

on:
  push:
    branches:
      - main
    paths:
      - "uv.lock"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13' # Specify the desired Python version
#          enable-cache: false

      - name: Install dependencies and populate cache
        run: |
          echo "Building global UV cache..."
          uv sync --all-groups
          echo "Cache populated successfully"

#      - name: Install dependencies
#        run: uv pip install -r requirements.txt # Or uv pip sync requirements.lock

      - name: Run Unit Tests with Coverage
        run: |
          uv run -- coverage run -m pytest
          uv run -- coverage report --show-missing
